export const vehicles = [
  {
    ID: "rental__1",
    VehicleName: "Excavators",
    Use: "Digging, material handling, demolition, and trenching",
    Features: "Long arm with a bucket, rotating cab",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756285/excavator_fvmczd.png",
  },
  {
    ID: "rental__2",
    VehicleName: "Bulldozers",
    Use: "Pushing soil, sand, rubble, and other materials",
    Features: "Large front blade, tracked wheels",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756285/dozer_v2xwpg.png",
  },
  {
    ID: "rental__3",
    VehicleName: "Backhoe Loaders",
    Use: "Digging, loading, and material handling",
    Features: "Front loader bucket, rear backhoe, and four-wheel drive",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756694/backhoe_ef9kh1.png",
  },
  {
    ID: "rental__tt",
    VehicleName: "Tipper",
    Use: "Transporting loose materials like sand, gravel, and demolition waste",
    Features: "Open-box bed, hydraulic lift for unloading",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717760197/dumper-truck_jfv82d.png",
  },
  {
    ID: "rental__4",
    VehicleName: "Dump Trucks",
    Use: "Transporting loose materials like sand, gravel, and demolition waste",
    Features: "Open-box bed, hydraulic lift for unloading",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756286/tipper_peuloy.png",
  },
  {
    ID: "rental__5",
    VehicleName: "Cranes",
    Use: "Lifting and moving heavy materials vertically and horizontally",
    Features: "Boom, cables, and pulleys",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756285/crane_y52oaz.png",
  },
  {
    ID: "rental__7",
    VehicleName: "Motor Graders",
    Use: "Creating flat surfaces, road construction, and leveling",
    Features: "Long blade, adjustable height",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756818/motor-grader_akupch.png",
  },
  {
    ID: "rental__8",
    VehicleName: "Concrete Mixers",
    Use: "Mixing and transporting concrete",
    Features: "Rotating drum, truck-mounted",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756286/Concretemixer_ov226q.png",
  },
  {
    ID: "rental__9",
    VehicleName: "Trenchers",
    Use: "Digging trenches for laying pipes or cables",
    Features: "Trencher chain, conveyor system",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756934/track-trencher_zfhasr.png",
  },
  {
    ID: "rental__10",
    VehicleName: "Compactors",
    Use: "Compressing soil, gravel, or asphalt",
    Features: "Vibratory plate or drum, roller wheels",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756999/road_pz7hur.png",
  },
  {
    ID: "rental__11",
    VehicleName: "Forklifts",
    Use: "Lifting andTelescopic Boom Lifts",
    Features: "Forked lift, counterbalance weight",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756285/loader_nxfqju.png",
  },
  {
    ID: "rental__12",
    VehicleName: "Telehandlers",
    Use: "Lifting materials to heights, material handling",
    Features: "Telescopic boom, various attachments",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757071/telehandlers_e5iz6b.png",
  },
  {
    ID: "rental__13",
    VehicleName: "Scrapers",
    Use: "Earthmoving, scraping soil, and transporting it",
    Features: "Bowl, apron, and ejector",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756285/scrap_ykxpxu.png",
  },
  {
    ID: "rental__14",
    VehicleName: "Pile Drivers",
    Use: "Driving piles into the soil for foundation support",
    Features: "Heavy hammer, leads, and winches",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757125/pile-driver_yzvhrs.png",
  },
  {
    ID: "rental__15",
    VehicleName: "Skid Steer Loaders",
    Use: "Digging, lifting, and material handling in tight spaces",
    Features: "Compact frame, lift arms",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757203/skid-steer-loader_zwf1ig.png",
  },
  {
    ID: "rental__16",
    VehicleName: "Asphalt Milling Machines",
    Use: "Removing old asphalt layers before resurfacing",
    Features: "Rotating drum, cutting teeth",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757299/asphalt-milling-machine_owxpmi.png",
  },
  {
    ID: "rental__17",
    VehicleName: "Boom Lifts",
    Use: "Accessing high work areas, lifting workers and materials",
    Features: "Extendable boom, platform",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757347/boom-lift_l5gjg7.png",
  },
  {
    ID: "rental__18",
    VehicleName: "Hydraulic Breakers",
    Use: "Breaking concrete, asphalt, and rocks",
    Features: "Hydraulic hammer, chisel tool",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757459/hydraulic-breaker_esakeg.png",
  },
  {
    ID: "rental__19",
    VehicleName: "Road Rollers",
    Use: "Compacting and smoothing surfaces, especially roads",
    Features: "Large drum rollers, vibratory action",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757510/road-roller_wdr00u.png",
  },
  {
    ID: "rental__20",
    VehicleName: "Tractor-Loaders",
    Use: "Digging, loading, and material transport",
    Features: "Loader at the front, tractor design",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757562/loader_jklhfw.png",
  },
  {
    ID: "rental__21",
    VehicleName: "Hydraulic Excavators",
    Use: "Heavy-duty digging and material handling",
    Features: "Hydraulic systems, various attachments",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757625/bulldozer_cprohr.png",
  },
  {
    ID: "rental__22",
    VehicleName: "Tower Cranes",
    Use: "Lifting and placing materials at great heights",
    Features: "Tall structure, jib, and counterweights",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757740/lift_zfvc03.png",
  },
  {
    ID: "rental__23",
    VehicleName: "Off-Highway Trucks",
    Use: "Transporting large quantities of material over rough terrain",
    Features: "Large tires, heavy-duty design",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757785/truck_e3vxtk.png",
  },
  {
    ID: "rental__24",
    VehicleName: "Street Sweepers",
    Use: "Cleaning streets and construction sites",
    Features: "Brushes, vacuum system",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717757865/street-sweeper_ldhbm6.png",
  },
  {
    ID: "rental__25",
    VehicleName: "Tractor",
    Use: "Transfort thing to long or short distance",
    Features: "tractor",
    "IMG URL":
      "https://res.cloudinary.com/dppxcekqu/image/upload/v1717756286/tractor_njtuju.png",
  },
];
export const sellers = [
  {
    id: "1",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Nalgonda,Telangana",
    model: "Tractor Model 1",
    price: 45000,
    description: "Versatile tractor suitable for various agricultural tasks.",
    imagesList: [
      "./Assets/rentalImg/Sell/t1.jpg",
      "./Assets/rentalImg/Sell/t2.jpg",
      "./Assets/rentalImg/Sell/t3.jpg",
      "./Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567890",
  },
  {
    id: "2",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "LB Nagar, Hyderabad, Telangana",
    model: "Tractor Model 2",
    price: 48000,
    description:
      "Powerful tractor with advanced features for efficient farming.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567891",
  },
  {
    id: "3",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Kattangur,Nalgonda,Telangana",
    model: "Tractor Model 3",
    price: 42000,
    description:
      "Compact tractor suitable for small-scale farming and gardening.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567892",
  },
  {
    id: "4",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Mallaram,Nalgonda,Telangana",
    model: "Tractor Model 4",
    price: 50000,
    description: "Heavy-duty tractor for large-scale agricultural operations.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567893",
  },
  {
    id: "5",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Nalgonda,Telangana",
    model: "Tractor Model 5",
    price: 46000,
    description:
      "Efficient tractor with a high horsepower engine for demanding tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567894",
  },
  {
    id: "6",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Gudem,Nalgonda,Telangana",
    model: "Tractor Model 6",
    price: 49000,
    description:
      "Reliable tractor equipped with modern technology for precision farming.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567895",
  },
  {
    id: "7",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Gattu,Nalgonda,Telangana",
    model: "Tractor Model 7",
    price: 47000,
    description:
      "Sturdy tractor designed to handle tough terrain and heavy loads.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567896",
  },
  {
    id: "8",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Cheruvu,Nalgonda,Telangana",
    model: "Tractor Model 8",
    price: 51000,
    description:
      "Versatile tractor suitable for both agricultural and industrial use.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567897",
  },
  {
    id: "9",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Vaguneru,Nalgonda,Telangana",
    model: "Tractor Model 9",
    price: 48000,
    description:
      "Compact tractor with excellent maneuverability for tight spaces.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567898",
  },
  {
    id: "10",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "MarrigudaNalgonda,Telangana",
    model: "Tractor Model 10",
    price: 52000,
    description:
      "Heavy-duty tractor with a comfortable cabin for long hours of operation.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567899",
  },
  {
    id: "11",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 1",
    price: 60000,
    Location: "Nalgonda",
    description:
      "Heavy-duty tipper truck suitable for bulk material transportation.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567890",
  },
  {
    id: "12",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 2",
    price: 55000,
    Location: "Nalgonda",
    description:
      "Durable tipper truck with a large capacity for industrial use.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567891",
  },
  {
    id: "13",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 3",
    price: 58000,
    Location: "Nalgonda",
    description:
      "Efficient tipper truck for construction and material hauling.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567892",
  },
  {
    id: "14",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 4",
    Location: "Nalgonda",
    price: 62000,
    description: "Reliable tipper truck for heavy-duty transportation tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567893",
  },
  {
    id: "15",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 5",
    price: 57000,
    Location: "Nalgonda",
    description:
      "Robust tipper truck designed for tough construction environments.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567894",
  },
  {
    id: "16",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 6",
    price: 63000,
    Location: "Nalgonda",
    description:
      "High-capacity tipper truck for large-scale material transport.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567895",
  },
  {
    id: "17",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 7",
    price: 59000,
    Location: "Nalgonda",
    description:
      "Versatile tipper truck suitable for various construction projects.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567896",
  },
  {
    id: "18",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 8",
    price: 65000,
    Location: "Nalgonda",
    description:
      "Heavy-duty tipper truck with advanced features for efficient operation.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567897",
  },
  {
    id: "19",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 9",
    price: 60000,
    Location: "Nalgonda",
    description:
      "Reliable tipper truck for construction and industrial applications.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567898",
  },
  {
    id: "20",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 10",
    price: 62000,
    Location: "Nalgonda",
    description:
      "Sturdy tipper truck designed to withstand heavy loads and rough terrain.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567899",
  },
  {
    id: "21",
    vehicle: "Backhoe Loaders",
    owner: "Peter",
    model: "Loader Model 1",
    price: 75000,
    Location: "Nalgonda",
    description:
      "Heavy-duty loader for construction and material handling tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567800",
  },
  {
    id: "22",
    vehicle: "Backhoe Loaders",
    owner: "Peter",
    model: "Loader Model 2",
    Location: "Nalgonda",
    price: 80000,
    description:
      "Versatile loader with a large bucket capacity for various applications.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567801",
  },
  {
    id: "221",
    vehicle: "Dump Trucks",
    owner: "John",
    model: "Truck Model A",
    price: 85000,
    Location: "Hyderabad",
    description:
      "Heavy-duty truck suitable for long-distance transport and heavy loads.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567810",
  },
  {
    id: "23",
    vehicle: "Cranes",
    owner: "Michael",
    model: "Crane Model B",
    price: 95000,
    Location: "Warangal",
    description:
      "High-capacity crane for construction and heavy lifting tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567820",
  },
  {
    id: "24",
    vehicle: "Excavators",
    owner: "Alice",
    model: "Excavator Model C",
    price: 105000,
    Location: "Vijayawada",
    description: "Powerful excavator ideal for digging and earth-moving tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567830",
  },
  {
    id: "25",
    vehicle: "Bulldozers",
    owner: "Emma",
    model: "Dozer Model D",
    price: 95000,
    Location: "Khammam",
    description: "Heavy-duty dozer for land clearing and grading tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567840",
  },
  {
    id: "26",
    vehicle: "Scrapers",
    owner: "Olivia",
    model: "Scrap Handler Model E",
    price: 65000,
    Location: "Karimnagar",
    description: "Efficient scrap handler for recycling and material handling.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567850",
  },
  {
    id: "27",
    vehicle: "Concrete Mixers",
    owner: "Liam",
    model: "Concrete Mixer Model F",
    price: 55000,
    Location: "Mahbubnagar",
    description: "Reliable concrete mixer for construction and paving tasks.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567860",
  },
  {
    id: "28",
    vehicle: "Motor Graders",
    owner: "Noah",
    model: "Motor Graders Model G",
    price: 125000,
    Location: "Rangareddy",
    description:
      "High-efficiency crusher plant for stone and aggregate processing.",
    imagesList: [
      "../Assets/rentalImg/Sell/t1.jpg",
      "../Assets/rentalImg/Sell/t2.jpg",
      "../Assets/rentalImg/Sell/t3.jpg",
      "../Assets/rentalImg/Sell/t4.jpg",
    ],
    contactNumber: "1234567870",
  },
];
